namespace cotto_system.Modelos.ComercializacionModelo
{
    public class Calculo:Tarjeta
    {
        public int idcalculo { get; set; }
        public int idcomprador { get; set; }
        public int idcliente { get; set; }
        public int idunidadventa { get; set; }
        public decimal valorunidad { get; set; }
        public decimal precio { get; set; }
        public decimal puntos { get; set; }
        public decimal preciosm { get; set; }
        public decimal preciom { get; set; }
        public decimal preciomp { get; set; }
        public decimal precioslmp { get; set; }
        public decimal precioslm { get; set; }
        public decimal preciolmp { get; set; }
        public decimal preciolm { get; set; }
        public decimal preciosgo { get; set; }
        public decimal preciogo { get; set; }
        public decimal precioo { get; set; }
        public int cantidadpacas { get; set; }
        public bool activatara { get; set; }
        public decimal valortara { get; set; }
        public int idperfilventa { get; set; }
        public bool activamic { get; set; }
        public int idperfilmic { get; set; }
        public decimal castigomic { get; set; }
        public bool activauhml { get; set; }
        public int idperfiluhml { get; set; }
        public decimal castigouhml { get; set; }
        public bool activastr { get; set; }
        public int idperfilstr { get; set; }
        public decimal castigostr { get; set; }
        public bool activauni { get; set; }
        public int idperfiluni { get; set; }
        public decimal castigouni { get; set; }
        public bool activasfi { get; set; }
        public int idperfilsfi { get; set; }
        public decimal castigosfi { get; set; }
        public decimal subtotal { get; set; }
        public decimal castigototal { get; set; }
        public decimal preciototal { get; set; }
        public string observaciones { get; set; }
        public string nombrecomprador { get; set; }
        public string nombrecliente { get; set; }
        public decimal parametro { get; set; }
        public int idcalculodet { get; set; }
        public string lotid { get; set; }
        public long baleid { get; set; }
        public string balegroup { get; set; }
        public string operador { get; set; }
        public DateTime date { get; set; }
        public decimal temperature { get; set; }
        public decimal humidity { get; set; }
        public decimal amount { get; set; }
        public decimal uhml { get; set; }
        public decimal ui { get; set; }
        public decimal strength { get; set; }
        public decimal elongation { get; set; }
        public decimal sfi { get; set; }
        public decimal maturity { get; set; }
        public string grade { get; set; }
        public decimal moist { get; set; }
        public decimal mic { get; set; }
        public decimal rd { get; set; }
        public decimal plusb { get; set; }
        public string colorgrade { get; set; }
        public int trashcount { get; set; }
        public decimal trasharea { get; set; }
        public int trashid { get; set; }
        public int sci { get; set; }
        public int nep { get; set; }
        public decimal uv { get; set; }
        public decimal kilos { get; set; }
        public decimal preciopaca { get; set; }
        public decimal precioclase { get; set; }
        public decimal valorpeso { get; set; }
        public decimal castigores { get; set; }
        public int idreciba { get; set; }
        public int idproveedor { get; set; }
        public int idzona { get; set; }
        public int idgin { get; set; }
        public int idtemporada { get; set; }
    }
}
